language: java
install: mvn -f build-pom.xml install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn -f build-pom.xml verify

notifications:
  email: cgruber@google.com

branches:
  except:
    - gh-pages
